### ISSUE TITLE
Managed Instance MAX IOPS is missing the 256GB Drives

### ISSUE THREAD

**Issue by MillenniumV3** [dimitri-furman/managed-instance#3]
should be:

BlobLimit AS
(
SELECT 128 AS BlobSizeGB, 500 AS IOPSLimit, 100 AS ThroughputLimit
UNION
SELECT 256, 1100, 125
UNION
SELECT 512, 2300, 150
UNION
SELECT 1024, 5000, 200
UNION
SELECT 2048, 7500, 250
),

https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/resource-limits#file-io-characteristics-in-general-purpose-tier

**Comment by dimitri-furman** [comment]
Hi @MillenniumV3 - Managed Instance does not use 256 GB (P15) blobs. Documentation was incorrect and has been updated. Thanks for reporting this discrepancy. I also updated this script to include larger blobs (P50, P60) that may be used as data files on Managed Instance.
